library(datasets)
library(WDI)
library(lubridate)
library(forecast)
library(ggplot2)
head(HairEyeColor)
names(HairEyeColor)
names(mtcars)
str(HairEyeColor)
dim(HairEyeColor)
#update world bank
WDIcache()
WDIsearch("lifeexpectantcy")
dat = WDI(indicator='NY.GDP.PCAP.KD', country=c('MY','AG','AR'), start=1960, end=1962)
dat
crash <- read.csv("airAccs.csv", header = T, stringsAsFactors = F)
crash[ , 2 ] <- ymd(crash[, 2])
crash$ID <- seq.int(nrow(crash))
#crash[c(4500:4525),c(2,4)]
dim(crash)
head(crash)
library(dplyr)
crashUSA <- crash %>% filter(grepl("US",operator))
dim(crashUSA)
crashUnitedStates <- crash %>% filter(grepl("United States",operator))
crashAmerica <- crash %>% filter(grepl("America", operator))
crashDelta <- crash %>% filter(grepl("Delta", operator))
crashHawaii <- crash %>% filter(grepl("Hawaii", operator))
crashSouthWest <- crash %>% filter(grepl("Southwest", operator))
crashAlaska <- crash %>% filter(grepl("Alaska", operator))
crashFrontier <- crash %>% filter(grepl("Frontier", operator))
crashUPS <- crash %>% filter(grepl("UPS", operator))
dim(crashEnvoy)
crashEnvoy

lear <- crash %>% filter(grepl("Lear",planeType))
boeing <- crash %>% filter(grepl("Boeing",planeType))
lear
head(boeing,50)
dim(boeing)
dim(crashSouthWest)
str(crashSouthWest)
dim(crashUnitedStates)
crashUS <- rbind(crashUSA, crashUnitedStates, crashAmerica, crashDelta, crashHawaii, crashSouthWest, crashAlaska, crashFrontier, crashUPS)
dim(crashUS)
duplicated(crashUS)
crashRussia <- crash %>% filter(grepl("Aerof",operator))
listRussia <- 1:270
airlineCountry <- rep("Russia", length(listRussia))
crashRussia1 <- cbind(crashRussia, airlineCountry)
head(crashRussia1)
crashRussia$Country <- crashRussia$Country("Russia")
head(crashRussia)
dim(crashRussia)
tail(crashRussia)
plot(crashRussia)
i <- ggplot(crashGerman, aes(Dead)) + geom_dotplot(color = "blue")
i
twoCountries <- rbind(crashGerman, crashRussia)
twoCountries
i <- ggplot(twoCountries, aes(Dead)) + geom_dotplot(color = "blue")
i
