---
title: "R Notebook"
output: html_notebook
---

**1. Load necessary libraries**

```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(GGally)
library(knitr)
library(ggplot2)
library(dplyr)
library(corrr)
library(MASS)
library(corrgram)

```



```{r}
Cluster <- read.csv("clusteringData.csv", 
                   header = T, stringsAsFactors = F)
kable(head(Cluster))
sapply(Cluster, class)
```

```{r}
#get rid of percent sign
Cluster$Positive_Profitability = as.numeric(gsub("\\%", "", Cluster$Positive_Profitability))
Cluster$Profitability = as.numeric(gsub("\\%", "", Cluster$Profitability))
#Verify no percent sign
kable(head(Cluster) %>% arrange(Profitability)) 
#convert profitability and positive profitability to numeric
Cluster$Positive_Profitability <- as.numeric(Cluster$Positive_Profitability)
Cluster$Profitability <- as.numeric(Cluster$Profitability)

#if need to convert them to integer
# Cluster$Profitability <- as.integer(Cluster$Profitability)
# Cluster$Positive_Profitability <- as.integer(Cluster$Positive_Profitability)
Cluster$Account_Open_Date <- as.Date(Cluster$Account_Open_Date , format = "%m/%d/%Y")
#verify class change
sapply(Cluster, class)
kable(head(Cluster)) 
```


```{r}
summary(Cluster)
```


```{r}
set.seed(121)
sampleSet <- sample_n(Cluster, 30)
str(sampleSet)
head(sampleSet)
ggplot(sampleSet, aes(x = Profitability, y = Card_Fees_Amt)) + geom_point(alpha = 0.1, color = "blue")+ geom_smooth(method = "lm")
ggplot(sampleSet, aes(x = Profitability, y = Card_Fees_Amt)) + geom_point() + scale_x_log10() + scale_y_log10() + geom_smooth(method = "lm")


ggplot(sampleSet, aes(x = Positive_Profitability, y = Card_Fees_Amt, color = factor(Average_Risk_Grade))) + geom_point(alpha = 0.3)

ggplot(sampleSet, aes(x = Positive_Profitability, y = Card_Fees_Amt, color = factor(Average_Risk_Grade))) + geom_point(alpha = 0.3) + facet_wrap(~ Average_Risk_Grade)


```


```{r}
newdata = sampleSet[,c(3:4, 5:18)]
plot(newdata, pch=16, col="blue", main="Matrix Scatterplot of ...")

mod1 = lm(Positive_Profitability ~ Average_Gallons_Card + Net_Late_Fee_Count +Net_Profit_Card + Years_on_Books + Card_Fees_Amt +No_Accounts_by_Customer + Rebate_Amt + Average_Risk_Grade + Gross_Revenue_Amt+ Purchase_Gallons_Qty, data=sampleSet)
summary(mod1)
```

```{r}
names(newdata)
```


```{r}
mod2 = lm(Positive_Profitability ~ Average_Gallons_Card + Max_of_Cards + Net_Late_Fee_Count + Total_Expense_Amt + Net_Profit + Net_Profit_Card + Years_on_Books + Card_Fees_Amt + No_Accounts_by_Customer + Rebate_Amt + Average_Risk_Grade + Gross_Revenue_Amt+ Purchase_Gallons_Qty + Acquisition_Cost, data=sampleSet)
summary(mod2)

```


```{r}
mod3 <- lm(Positive_Profitability ~ Average_Gallons_Card + Max_of_Cards + Total_Expense_Amt + Net_Profit_Card + Years_on_Books + Purchase_Gallons_Qty + Acquisition_Cost, data = sampleSet)
summary(mod3)
```

```{r}
library(dplyr)
head(sampleSet)
dim(sampleSet)
names(sampleSet)
sampleSet <- sampleSet[, -c(1:3, 5, 7, 9, 11:13, 17:19 )]
dim(sampleSet)
head(sampleSet)

head(Cluster)

Cluster1 <- Cluster %>% dplyr::select(Positive_Profitability, Average_Risk_Grade, Average_Gallons_Card, Max_of_Cards, Total_Expense_Amt, Net_Profit_Card, Years_on_Books, Purchase_Gallons_Qty, Acquisition_Cost)
#Sig Variables 56%
c1 <- lm(Positive_Profitability ~  Average_Gallons_Card+ Max_of_Cards + Total_Expense_Amt + Net_Profit_Card + Years_on_Books + Purchase_Gallons_Qty + Acquisition_Cost, data = Cluster1)
summary(c1)

#Removed acquiaition 49%
c2 <- lm(Positive_Profitability ~ Average_Gallons_Card+ Max_of_Cards + Total_Expense_Amt + Net_Profit_Card + Years_on_Books + Purchase_Gallons_Qty, data = Cluster1)
summary(c2)

#removed acquisition and Purchase gallons 43%
c3 <- lm(Positive_Profitability ~ Average_Gallons_Card+ Max_of_Cards + Total_Expense_Amt + Net_Profit_Card + Years_on_Books, data = Cluster1)
summary(c3)

#removed acquisition and Purchase gallons, Years_on_Books 40%
c4<- lm(Positive_Profitability ~ Average_Gallons_Card+ Max_of_Cards + Total_Expense_Amt + Net_Profit_Card, data = Cluster1)
summary(c4)

#removed acquisition and Purchase gallons, Years_on_Books, NetProfit_Card 33%
c4<- lm(Positive_Profitability ~ Average_Gallons_Card+ Max_of_Cards + Total_Expense_Amt,  data = Cluster1)
summary(c4)

#removed acquisition and Purchase gallons, Years_on_Books, NetProfit_Card .02%
c4<- lm(Positive_Profitability ~ Average_Gallons_Card+ Max_of_Cards,  data = Cluster1)
summary(c4)

#Net Profit Card 
c4<- lm(Positive_Profitability ~  Net_Profit_Card,  data = Cluster1)
summary(c4)

#Net Profit Card 
c4<- lm(Positive_Profitability ~  Average_Gallons_Card ,  data = Cluster1)
summary(c4)

#Max_Cards 
c4<- lm(Positive_Profitability ~  Max_of_Cards,  data = Cluster1)
summary(c4)


#Max_Cards 
c4<- lm(Positive_Profitability ~  Years_on_Books,  data = Cluster1)
summary(c4)

#Purchase_Gallons_Qty 
c4<- lm(Positive_Profitability ~ Purchase_Gallons_Qty,  data = Cluster1)
summary(c4)

#Acquisition_Cost 
c4<- lm(Positive_Profitability ~ Acquisition_Cost,  data = Cluster1)
summary(c4)




head(Cluster1)
summary(Cluster1)
set.seed(201)
cluster1Smple <- sample_n(Cluster1, 40) %>% na.omit()
summary(cluster1Smple)
head(cluster1Smple)
kc <- kmeans(cluster1Smple[, 3:9], 4, nstart = 20)
kc$centers
kc$size

table(kc$cluster, cluster1Smple$Average_Risk_Grade)
kc$cluster <- as.factor(kc$cluster)

ggplot(cluster1Smple, aes(Total_Expense_Amt, Years_on_Books, color = kc$cluster, alpha = 0.1)) + geom_point()

ggplot(cluster1Smple, aes(Max_of_Cards, Total_Expense_Amt, color = kc$cluster, alpha = 0.5)) + geom_point()

head(cluster1Smple)


# clusters <- hclust(dist(cluster1Smple[, 3:9],3, nstart = 20))
# plot(clusters)


```

```{r}
library(dendextend)
library(circlize)

irisCluster <- kmeans(cluster1Smple[, 3:9], 3, nstart = 20)
irisCluster$centers

# create a dendrogram
hc <- hclust(dist(cluster1Smple[, 3:9]))
dend <- as.dendrogram(hc)

# modify the dendrogram to have some colors in the branches and labels
dend <- dend %>% 
   color_branches(k=3) %>% 
   color_labels

# plot the radial plot
par(mar = rep(0,4))
# circlize_dendrogram(dend, dend_track_height = 0.8) 
circlize_dendrogram(dend, labels_track_height = NA, dend_track_height = .3) 
```


```{r}
# Create the dend:
hc <- hclust(dist(cluster1Smple), "ave")
d <- as.dendrogram(hc)
library(dendextend)
d <- d %>% color_branches(k=3) %>% color_labels

# horiz normal version
par(mar = c(3,1,1,7))
plot(d, horiz  = TRUE)

plot(d, type = "triangle", ylab = "Height")
```


```{r}
# Define nodePar
nodePar <- list(lab.cex = 0.6, pch = c(NA, 19), 
                cex = 0.7, col = "blue")
# Customized plot; remove labels
plot(d, ylab = "Height", nodePar = nodePar, leaflab = "none", horiz = T)
```


```{r}
library(ape)
dd <- as.phylo(d)
plot(as.phylo(d), type = "unrooted", cex = 0.6,
     no.margin = TRUE)
```


```{r}
colors = c("red", "blue", "green", "black")
clus4 = cutree(d, 4)
plot(as.phylo(d), type = "fan", tip.color = colors[clus4],
     label.offset = 1, cex = 0.7)
```


**Principle Component Analysis**

```{r}
cluster1Smple <-  cluster1Smple[, c(1:3, 6:7, 9)]
head(cluster1Smple)
dim(cluster1Smple)
library("factoextra")
library("FactoMineR")
res.pca <- PCA(cluster1Smple, graph = FALSE)
res.pca
```

Eigenvalues: The amount of variation retained by each principle component. The first PC corresponds to the direction with the maximum amount of variation in the data set.

```{r}
eigenvalues <- res.pca$eig
eigenvalues[, 1:3]
```

```{r}
fviz_screeplot(res.pca, ncp = 10)
```

Correlation circle can help to visualize the most correlated variables (i.e, variables that group together).

```{r}
head(res.pca$var$coord)
fviz_pca_var(res.pca)
```

```{r}
head(res.pca$var$cos2)
```
```{r}
fviz_pca_var(res.pca, col.var="cos2") +
scale_color_gradient2(low="white", mid="blue", 
                    high="red", midpoint=0.5) + theme_minimal()
```

```{r}
head(res.pca$var$contrib)
```
```{r}
fviz_pca_contrib(res.pca, choice = "var", axes = 1)

```
```{r}
# Contributions of variables on PC2
fviz_pca_contrib(res.pca, choice = "var", axes = 2)
```
```{r}
# Total contribution on PC1 and PC2
fviz_pca_contrib(res.pca, choice = "var", axes = 1:2)
```
```{r}
# Control variable colors using their contributions
fviz_pca_var(res.pca, col.var="contrib")
```



```{r}
res.desc <- dimdesc(res.pca, axes = c(1,2))
# Description of dimension 1
res.desc$Dim.1
```
```{r}
# Description of dimension 2
res.desc$Dim.2
```

```{r}
head(res.pca$ind$coord)
fviz_pca_ind(res.pca)
```
```{r}
# Contributions of the individuals to PC1
fviz_pca_contrib(res.pca, choice = "ind", axes = 1, top = 10)
```


```{r}
clusterZ <- cluster1Smple %>% mutate(marketingCost = Acquisition_Cost + 5)
head(clusterZ)

cs <- clusterZ %>% mutate(Positive_ProfitabilityZ = scale(Positive_Profitability), AvRiskGrZ = scale(Average_Risk_Grade) ,AvGallCardZ = scale(Average_Gallons_Card), NetProfitCardZ = scale(Net_Profit_Card), YrZ = scale(Years_on_Books), MarketZ = scale(marketingCost))
dim(cs)
cs <- cs %>% dplyr::select(Positive_ProfitabilityZ, AvRiskGrZ, AvGallCardZ, NetProfitCardZ, YrZ)
head(cs)
dim(cs)

Customer <- seq(from=1, to=200, by=1)
head(Customer)
names(cluster1Smple)
clusterLong <- gather(cs, variable, value,Positive_ProfitabilityZ:YrZ)
dim(clusterLong)
ClusterData <- cbind.data.frame(Customer, clusterLong)

ClusterData$variable <- as.factor(ClusterData$variable)
ClusterData$Customer <- as.character(ClusterData$Customer)
head(ClusterData)
ggplot(ClusterData, aes(x = value, fill = variable)) + geom_histogram() + facet_grid(~variable)
ggplot(ClusterData, aes(x=value, fill=variable)) + geom_density()
ggplot(ClusterData, aes(x=value, colour=variable)) + geom_density(size = 2) + theme_bw()
```


```{r}
# Density plots with semi-transparent fill
ggplot(ClusterData, aes(x=rating, fill=cond)) + geom_density(alpha=.3)
```

```{r}
ggplot(ClusterData, aes(x=value)) + geom_histogram(binwidth=.5, colour="black", fill="white") + 
    facet_grid(variable ~ .)
```


**1**

```{r}
set.seed(201)
cluster2Sample <- sample_n(Cluster1, 1000) %>% na.omit()

head(cluster2Sample)
dat <- cluster2Sample[, 3:9] # without known classification 
# Kmeans clustre analysis
clus <- kmeans(dat, centers=3)
# Fig 01
plotcluster(dat, clus$cluster)
```

**2**

```{r}
dat <- cluster2Sample[, 3,5:9] # without known classification 
# Kmeans clustre analysis
clus <- kmeans(dat, centers=3)
# Fig 01
plotcluster(dat, clus$cluster)
```

**3**
```{r}
dat <- cluster2Sample[, 3:4,6:9] # without known classification 
# Kmeans clustre analysis
clus <- kmeans(dat, centers=3)
# Fig 01
plotcluster(dat, clus$cluster)
```

**4**
```{r}
dat <- cluster2Sample[, 3:5, 7:9] # without known classification 
# Kmeans clustre analysis
clus <- kmeans(dat, centers=3)
# Fig 01
plotcluster(dat, clus$cluster)
```


**5**

```{r}
dat <- cluster2Sample[, 3:6, 8:9] # without known classification 
# Kmeans clustre analysis
clus <- kmeans(dat, centers=3)
# Fig 01
plotcluster(dat, clus$cluster)
```


**6**

```{r}
dat <- cluster2Sample[, 3:7,9] # without known classification 
# Kmeans clustre analysis
clus <- kmeans(dat, centers=3)
# Fig 01
plotcluster(dat, clus$cluster)
```

```{r}
head(iris)
dim(iris)
set.seed(20)
irisCluster <- kmeans(iris[, 3:4], 3, nstart = 20)
irisCluster
```


```{r}

ggcorr(Cluster1, label = T)
corrgram(as.matrix(Cluster1), order = NULL, panel = panel.shade, text.panel = panel.txt, main = "Correlogram")
```




```{r, echo=TRUE}

fit <- lm(Profitability ~  Net_Late_Fee_Count + Acquisition_Cost + Net_Profit +  Years_on_Books +  Average_Risk_Grade, data=Cluster)
summary(fit) # show results
Cluster <- Cluster %>% dplyr::select(Random, Customer_Index, Profitability, Net_Late_Fee_Count, Acquisition_Cost, Net_Profit, Years_on_Books)
Cluster <- as.matrix(Cluster)
head(Cluster)


```




```{r}
library(reshape2)
Long <- melt(sampleSet, id= c("Random", "Customer_Index"))
Long[8000, ]
head(newdata)
ggplot(newdata, aes(x = Positive_Profitability, y = Max_of_Cards )) + geom_point() + geom_smooth(method = "lm")
                      #,color = factor(Years_on_Books
                                     
ggplot(newdata, aes(x = Positive_Profitability, y = Gross_Revenue_Amt )) + geom_point() + geom_smooth(method = "lm")

ggplot(newdata, aes(y = Positive_Profitability, x = Card_Fees_Amt )) + geom_point() + geom_smooth(method = "lm")

```


