---
title: "Homicidepractice"
author: "Christine Iyer"
date: "May 7, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)


```


```{r}
library(plyr)
library(dplyr)
library(tidyr)
library(data.table)
library(zoo)
library(knitr)
library(ggplot2)
```


```{r, message=FALSE, warning=FALSE}
#Dates
setwd("/Users/Chris Iyer/Documents/R/myrepo/Homicide/")
homicide <- read.csv("Homicide.csv")
homicide <- as_data_frame(homicide)
homicide1 <-  homicide %>% select(Month, Year)
homicide1 <- homicide1 %>% mutate(month = ifelse(Month == "January", "01",
 ifelse(Month == "February", "02",ifelse(Month == "March", "03",
 ifelse(Month == "April", "04",ifelse(Month == "May", "05",
 ifelse(Month == "June", "06",ifelse(Month == "July", "07",
 ifelse(Month == "August", "08",ifelse(Month == "September", "09",
 ifelse(Month == "October", "10",ifelse(Month == "November", "11","12"))))))))))))
homicide1$Year <- as.character(homicide1$Year)
homicide1 <- transform(homicide1, newcol = paste(Year,"/", month,"/01", sep = ""))
homicide1$newcol <-  as.Date(homicide1$newcol, format = "%Y/%m/%d")
class(homicide1$newcol)
homicide1 <- homicide1 %>% select(Date = newcol)
Homicide <- cbind.data.frame(homicide1, homicide)
Homicide <- Homicide %>% select(1, 6:8, 10:23)
head(Homicide)
# sapply(Homicide, class)
# set.seed(201)
# Homicide <- Homicide[sample(nrow(Homicide), 100), ]
# dim(Homicide)
```


```{r}
homicideA <- Homicide %>% select(Year,City, Weapon)%>% group_by(City, Year) %>% summarise(countA = n())  %>% arrange(desc(countA)) %>% top_n(10)
head(homicide)
homicideB <- Homicide %>% group_by(City, State) %>% summarise(TotalH = n()) %>% select(City, State, TotalH)
head(homicideB)
homicideB <- homicideB %>% mutate(Location = (paste(City, ",", State))) %>% group_by(Location) %>% summarise(TotalH)
                                  
                                  
                                  
head(homicideB)
dim(homicideB)

Most <- homicideB %>% arrange(desc(TotalH)) %>%  top_n(20)
kable(Most)
```


```{r}
ID <- c("P1", "P1", "P2", "P2", "P3", "P3")
Value1 <- c(100,120,300,400,130,140)
Value2 <- c(12,13,11,16,15,12)
dat <- cbind.data.frame(ID,Value1,Value2)
dat


ggplot(subset(dat,ID %in% c("P1" , "P3"))) + 
         geom_line(aes(Value1, Value2, group=ID, colour=ID))
ggplot(data=dat)+ 
  geom_line(aes(Value1, Value2, group=ID, colour=ID), subset = (ID %in% c("P1" , "P3")))+ theme_bw()


```


```{r}
ggplot(Homicide, aes(Year))+ geom_bar(aes(fill = Crime.Solved))

ggplot(Homicide, aes(Year)) + geom_bar(aes(fill = Perpetrator.Race %in% c("Black", "White")))
```



```{r}
#Black and White on Black on White
BlackonWhite <- Homicide %>% filter(Perpetrator.Race == "Black" & Victim.Race=="White") %>% select(Date, Year, City, State, Perpetrator.Race, Victim.Race, Weapon,Incident)
head(BlackonWhite)
dim(BlackonWhite)
```

```{r}
byWeapBonW <- group_by(BlackonWhite, Weapon) 
head(byWeapBonW)
```

```{r}
BlonWhYear <- group_by(byWeapBonW, Year)
head(BlonWhYear)
dim(BlonWhYear)
names(BlonWhYear)
```


```{r}
WhiteonBlack <- Homicide %>% filter(Perpetrator.Race == "White" & Victim.Race=="Black") %>% select(Date, Year, City, State, Perpetrator.Race, Victim.Race, Weapon, Incident) 
head(WhiteonBlack)
dim(WhiteonBlack)
```

```{r}
byWeapWonB <- group_by(WhiteonBlack, Weapon)
head(byWeapWonB)

```

```{r}
sumWeapWonB <- summarise(byWeapWonB, count = n())
```

```{r}
WhonBlYear <- group_by(byWeapWonB, Year)
head(WhonBlYear)
dim(WhonBlYear)
b <- ggplot(Homicide, aes(Year))
b + geom_bar(aes(fill = Victim.Race))
Solved <- Homicide %>% group_by(Year, Crime.Solved) %>% summarise(countSol = n())
head(Solved)
Yearly <- group_by(Homicide, Year)
head(Yearly)
YearRace <-  Yearly %>%  group_by(Year, Perpetrator.Race)
YearCounts <- summarise(Yearly, count = n())
RaceCounts <- summarise(YearRace, countn = n())
head(RaceCounts, 20)
dim(RaceCounts)
colors <- c("red","blue", "green", "yellow", "orange")
head(YearCounts)
a <- ggplot(data = RaceCounts, aes(x = Year, y = countn, group = Perpetrator.Race, color = Perpetrator.Race, shape = Perpetrator.Race)) + 
    geom_line(size=1.5) + 
    geom_point(size=3, fill="white") +
    scale_shape_manual(values=c(22,21, 22,23,24))+
    xlab("Year") + ylab("Total Homicides")
a

a <- ggplot(data = RaceCounts, aes(x = Year, y = countn, group = Perpetrator.Race, color = Perpetrator.Race, shape = Perpetrator.Race)) + 
    geom_line(size=1) + 
    xlab("Year") + ylab("Total Homicides")
a


ggplot(data = Solved, aes(x = Year, y = countSol, fill = Crime.Solved, color = Crime.Solved)) + geom_line(linetype="dashed",size=1.2)+
  scale_color_manual(values=c("#999999", "#E69F00"))+
  scale_color_brewer(palette="Dark2")
  
  # geom_point(color="red", size=3)
    #geom_bar(stat="identity", position=position_dodge())
```


```{r}
ggplot(Homicide, aes(State))+ geom_bar(aes(fill = Crime.Solved)) +
  coord_flip()
ggplot(Homicide, aes(State))+ geom_bar(aes(fill = Perpetrator.Race)) +
  coord_flip()
```





```{r}
a <- ggplot(Homicide,aes(Weapon))
a  + geom_bar()
b <- ggplot(Homicide, aes(Perpetrator.Race))
```



```{r}
b + geom_bar(color = "Red", fill = "Orange")
```









