---
title: "R Notebook"
output: html_notebook
---

```{r}
library(lubridate)
library(dplyr)
library(knitr)
library(tidyr)
library(ggplot2)
```


```{r}

Kentucky <- read.csv("Kentucky.csv", header = T)
Kentucky <- Kentucky %>% rename(Male_1985 = Male.life.expectancy..1985..years., 
                                Female_1985 = Female.life.expectancy..1985..years., 
                                Male_1990 = Male.life.expectancy..1990..years., 
                                Female_1990 = Female.life.expectancy..1990..years., 
                                Male_1995 = Male.life.expectancy..1995..years., 
                                Female_1995 = Female.life.expectancy..1995..years., 
                                Male_2000 = Male.life.expectancy..2000..years., 
                                Female_2000 = Female.life.expectancy..2000..years., 
                                Male_2005 = Male.life.expectancy..2005..years., 
                                Female_2005 = Female.life.expectancy..2005..years., 
                                Male_2010 = Male.life.expectancy..2010..years., 
                                Female_2010 = Female.life.expectancy..2010..years.,
                                MaleDifference = Difference.in.male.life.expectancy..1985.2010..years., 
                                FemaleDifference = Difference.in.female.life.expectancy..1985.2010..years.) %>% 
  select(State.County, Male_1985, Male_1990, Male_1995, Male_2000, Male_2005, Male_2010, Female_1985, Female_1990, Female_1995, Female_2000, Female_2005, Female_2010)

names(Kentucky)

head(Kentucky)

Kentucky <- Kentucky %>% gather(GenderYr, Age, Male_1985:Female_2010)
head(Kentucky)


Kentucky1 <- data.frame(do.call('rbind', strsplit(as.character(Kentucky$Gender),'_',fixed=TRUE)))
Kentucky1 <- Kentucky1 %>% mutate(Year_Number = ifelse(X2 == "1985", 0, ifelse(X2 =="1990", 5,ifelse(X2 == "1995", 10, ifelse(X2 == "2000", 15, ifelse(X2 == "2005", 20,25))))))
head(Kentucky1)
#Kentucky <-  do.call(rbind,str_split(Kentucky$Gender, '_'))

Kentucky11 <- cbind.data.frame(Kentucky, Kentucky1)
head(Kentucky11)

Kentucky11 <- Kentucky11 %>% rename(Gender = X1, Year = X2) %>% select(State.County, Year, Gender, Age, Year_Number)
kable(head(Kentucky11, 20))
kable(tail(Kentucky11, 20))
Kentucky11$Year_Number <- as.integer(Kentucky11$Year_Number)
Kentucky11$Age <- as.numeric(Kentucky11$Age)
head(Kentucky11)

```

```{r}
USnewDate <- data.frame("State.County" = character(), "Year" = character(), "Year_Number" = integer(), "Gender" = character(), "Age" = double(), stringsAsFactors = FALSE)
USnewDate[nrow(USnewDate)+1, ] <- c("United States", "2014", 29, "Male", 76.71)
USnewDate[nrow(USnewDate)+1, ] <- c("United States", "2014", 29, "Female", 81.45)
USnewDate
USnewDate1 <- USnewDate[1,]
USnewDate2 <- USnewDate[2,]
USnewDate1
USnewDate2
```

```{r}
KnewDate <- data.frame("State.County" = character(), "Year" = character(), "Year_Number" = integer(), "Gender" = character(), "Age" = double(), stringsAsFactors = FALSE)
KnewDate[nrow(KnewDate)+1, ] <- c("Kentucky", "2014", 29, "Male", 73.71)
KnewDate[nrow(KnewDate)+1, ] <- c("Kentucky", "2014", 29, "Female", 78.82)
KnewDate
KnewDate1 <- KnewDate[1,]
KnewDate2 <- KnewDate[2,]
KnewDate1
KnewDate2

```



**Subset by County**

```{r}
Kentucky2 <- Kentucky11 %>% filter(State.County == "Kentucky") %>% select(State.County, Year, Year_Number, Gender, Age)
tail(Kentucky2)
Kentucky2

newData1 <- rbind(Kentucky2[1:6, ],KnewDate1, Kentucky2[7:12,], KnewDate2 )
newData1

USA <- Kentucky11 %>% filter(State.County == "United States") %>% select(State.County, Year, Year_Number,Gender, Age)
head(USA)

newData2 <- rbind(USA[1:6, ], USnewDate1, USA[7:12, ], USnewDate2)
newData2

Kentucky2
USA
x <- rbind.data.frame(newData2, newData1)
x$Age <- as.numeric(x$Age)
x$Year_Number <- as.numeric(x$Year_Number)
x

```

```{r}
y <- x[c(1:14), ]
y <- y %>% rename(Country = State.County)
y
```

```{r}
z <- x[c(15:28), ]
z
colnames(z) <- c("State","YearK","Year_NumberK", "GenderK", "AgeK")
z
```

```{r}
combine <- cbind.data.frame(y,z)
combine
combine <- combine %>% mutate(difference = Age - AgeK, differenceK = Age - AgeK)
dim(combine)
combine
combineUnUA <- combine[, c(1:5,11)]
names(combineUnUA) <- c("State.County", "Year", "Year_Number", "Gender", "Age", "Difference")
combineUnUA

combineKen <-  combine[, c(6:10,11)]
names(combineKen) <- c("State.County", "Year", "Year_Number", "Gender", "Age", "Difference")
combineKen

NewlyCombined <- rbind.data.frame(combineUnUA, combineKen)
NewlyCombined
ymin <- rep(combine$AgeK,2)
ymin
ymax <- rep(combine$Age,2)
ymax
minmax <- cbind.data.frame(ymin, ymax)
minmax <- minmax %>% mutate(diff = ymax - ymin)
minmax
```


```{r}
mm <- ggplot(data = NewlyCombined, aes(x = Year, y = Difference, group = Gender, color = Gender)) + geom_line(size = 2) +
  ggtitle("Number Years the Average US Citizen \n Outives the Average Kentucker") 
#+ geom_smooth(method = "lm", se = FALSE, size = .5, color = "black")
              
mm
```

+ geom_ribbon(aes(x=Year_Number, ymax= Age.upper, ymin= Age.lower), fill="pink", alpha=.5)

```{r, echo=TRUE}
NewlyCombined
corYear <- cor(x$Year_Number, x$Age)
corYear


```


```{r}
x <- cbind.data.frame(x, minmax)
x
p <- ggplot(data = x, aes(x = Year, y = Age, group = State.County, color = State.County)) + 
  geom_line(size = 2.5) + 
  facet_wrap(~ Gender) +
  ggtitle("Life expectancy in Kentucky lags behind much of the US. \nAnd that gap widens each year. \n\nLet's blame Mitch McConnell. \n") +
  
  #so grey is not obscuring the legend
  geom_ribbon(aes(x=Year, ymin=ymin, ymax=ymax), fill="grey", alpha=.3, show_guide=FALSE) + 
  scale_color_manual(values=c("#330099", "#FF3300")) +
  theme_bw()+
  theme(legend.position='bottom', legend.direction='horizontal') 
#+ geom_smooth(method = "lm", se = FALSE, size = 0.025) 

p + theme(legend.title = element_blank()) +
  theme(plot.title=element_text(size=17, hjust=0.5,color="black")) +
  theme(plot.subtitle=element_text(size=13, hjust=0.5, color="black")) 


p <- ggplot(data = x, aes(x = Year, y = Age, group = State.County, color = State.County)) + geom_point(size = 2) + geom_line(size = 1.5) + facet_wrap(~Gender) + 
  scale_color_manual(values=c("#330099", "#FF3300")) +
  ggtitle("Life expectancy in Kentucky lags behind much of the US. \nAnd that gap widens each year. \n\nLet's blame Mitch McConnell. \n") 
p +
  theme_bw() + theme(legend.title = element_blank()) 
```


```{r}
m <- ggplot(data = x, aes(x = Year_Number, y = Age, group = Gender, color = Gender)) + geom_line(size = 1.5) + facet_wrap(~ State.County)
m
```


