---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)

```


```{r}
NewJersey <- read.csv("NJResearch.csv", header = T, stringsAsFactors = F)

NewJersey <- NewJersey[,1:8]
NewJersey <- t(NewJersey) 
NewJersey <- as.data.frame(NewJersey)

colnames(NewJersey) <- as.character(unlist(NewJersey[1,]))
NewJersey <- NewJersey[-1,]
dim(NewJersey)
City <- c("EastOrange",	
"Elizabeth",	
"JerseyCity",	
"Newark",	
"NewBrunswick",	
"Paterson",	
"Trenton")
NewJersey1 <- cbind(City, NewJersey)
newNames <- c("City", "TimeToPenn", "DistToPenn", "Population.number", "FemalePop", "MalePop", "Median.age", "Median.income", "PctPoverty", "Crime.index", "ViolCrimeper100K")

names(NewJersey1) <- sub(" ", "./()", names(NewJersey1))
NewJersey1
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
