---
title: "Polling"
author: "Christine Iyer"
date: "May 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r, message=FALSE, warning=FALSE}
library(rvest)
library(stringr)
library(reshape2)
library(knitr)
library(dplyr)
library(forecast)
library(ggplot2)
library(dplyr)
pollsData <- read_html("http://www.realclearpolitics.com/epolls/other/president_trump_job_approval-6179.html#polls")
```

 
```{r}
poll <- pollsData %>% html_nodes("#polling-data-full td.noCenter") %>% html_text()
poll
date <- pollsData %>% html_nodes("#polling-data-full .noCenter+ td") %>% html_text()
date
sample <- pollsData %>% html_nodes("#polling-data-full td.sample") %>% html_text()
sample
approve <- pollsData %>% html_nodes("#polling-data-full .sample+ td") %>% html_text()
approve
disapprove <- pollsData %>% html_nodes("#polling-data-full td:nth-child(5)") %>% html_text()
disapprove
spread <- pollsData %>% html_nodes("#polling-data-full td.spread") %>% html_text()
spread
Total <- cbind.data.frame(poll, date, sample, approve, disapprove, spread)
# kable(Total)
Total
write.csv(Total, "Polls.csv", row.names = F)
```

```{r}
Gallup <- Total %>% filter(poll == "GallupGallup")

Gallup$date <- (as.Date(c('2017-05-09', '2017-05-02' ,'2017-04-25', '2017-04-18', '2017-04-11', '2017-04-04', '2017-03-28', '2017-03-21', '2017-03-14', '2017-03-07', '2017-02-28', '2017-02-21', '2017-02-14', '2017-02-07', '2017-01-31', '2017-01-24')))

Gallup <- Gallup[nrow(Gallup):1, ]
Gallup$Week <- seq.int(nrow(Gallup))
kable(Gallup)
dim(Gallup)
```



```{r}
Rasmussen <- Total %>% filter(poll == "Rasmussen ReportsRasmussen")
Rasmussen$date <- (as.Date(c('2017-05-09', '2017-05-02' ,'2017-04-25', '2017-04-18', '2017-04-11', '2017-04-04', '2017-03-28', '2017-03-21', '2017-03-14', '2017-03-07', '2017-02-28', '2017-02-21', '2017-02-14', '2017-02-07', '2017-01-31', '2017-01-24')))

Rasmussen <- Rasmussen[nrow(Rasmussen):1, ]
Rasmussen$Week <- seq.int(nrow(Rasmussen))
Rasmussen$approve <- as.integer(Rasmussen$approve)
cor(Rasmussen$Week, Rasmussen$approve)
kable(Rasmussen)
dim(Rasmussen)
```

```{r}
Economist <- Total %>% filter(poll == "Economist/YouGovEconomist")
Economist$date <- (as.Date(c('2017-05-09', '2017-05-02' ,'2017-04-25', '2017-04-18', '2017-04-11', '2017-04-04', '2017-03-28', '2017-03-21', '2017-03-14', '2017-03-07', '2017-02-28', '2017-02-21', '2017-02-14', '2017-02-07', '2017-01-31', '2017-01-24')))

Economist <- Economist[nrow(Economist):1, ]
Economist$Week <- seq.int(nrow(Economist))

dim(Economist)
kable(Economist)
```


```{r}
Reuters <- Total %>% filter(poll == "Reuters/IpsosReuters")
Reuters$date <- (as.Date(c('2017-05-09', '2017-05-02' ,'2017-04-25', '2017-04-18', '2017-04-04', '2017-03-28', '2017-03-21', '2017-03-14', '2017-03-07', '2017-02-28', '2017-02-21', '2017-02-14', '2017-02-07', '2017-01-31', '2017-01-24')))
Reuters
a <- "Reuters/IpsosReuters"
b <- as.Date('2017-04-11')
c <- "1847A"
d <- "47"
e <- "48"
f <- "-1"
g <- cbind.data.frame(a,b,c,d,e,f)
g
g <- g %>% rename(poll = a, date = b, sample = c, approve = d, disapprove = e, spread = f)
Reuters1 <- rbind(g, Reuters)
Reuters1 <- Reuters1 %>% arrange(desc(date))
Reuters1
Reuters <- Reuters1
Reuters
Reuters <- Reuters[nrow(Reuters):1, ]
Reuters$Week <- seq.int(nrow(Reuters))
dim(Reuters)
kable(Reuters)

```


```{r}
Fox <- Total %>% filter(poll == "FOX NewsFOX News")
Fox
Fox$date <- (as.Date(c('2017-04-25','2017-03-14', '2017-02-13')))

Fox <- Fox[nrow(Fox):1, ]
Fox$Week <- seq.int(nrow(Fox))
Fox$approve <- as.integer(Fox$approve)
Fox
dim(Fox)
cor(Fox$Week, Fox$approve)
```


```{r}
CNN <- Total %>% filter(poll == "CNN/ORCCNN/ORC")
CNN$Week<- seq.int(nrow(CNN))
dim(CNN)
```


```{r}
CBS <- Total %>% filter(poll == "CBS NewsCBS News")
CBS
CBS$date <- (as.Date(c('2017-04-24', '2017-04-09', '2017-03-28', '2017-02-21',  '2017-02-02')))

CBS <- CBS[nrow(CBS):1, ]
CBS$Week <- seq.int(nrow(CBS))
kable(CBS)
dim(CBS)
ggplot(data = CBS, aes(x = date, y = approve)) + geom_line(size=1) 




```



```{r}
Pollsr <- rbind(CBS, Economist, Rasmussen, Reuters, Fox)
tail(Pollsr, 20)
a <- ggplot(data=Pollsr, aes(x=date, y= approve, group=poll, color = poll)) +
    geom_line(size=0.015) +geom_smooth(method = "lm", se = FALSE, linetype = 2)
a
```

```{r}
WaPoABC <- Total %>% filter(poll == "ABC News/Wash PostABC/WP")
WaPoABC$Week<- seq.int(nrow(WaPoABC))
dim(WaPoABC) 
```


```{r}
Quinnipiac <- Total %>% filter(poll == "QuinnipiacQuinnipiac")
Quinnipiac$Week<- seq.int(nrow(Quinnipiac))
dim(Quinnipiac)
```


```{r}
NBCWSJ <- Total %>% filter(poll == "NBC News/Wall St. JrnlNBC/WSJ")
NBCWSJ$Week<- seq.int(nrow(NBCWSJ))
dim(NBCWSJ)
```


```{r}
PPP <- Total %>% filter(poll == "PPP (D)PPP (D)")
PPP$Week<- seq.int(nrow(PPP))
dim(PPP)
 
```


```{r}
Marist <- Total %>% filter(poll == "MaristMarist")
Marist$Week<- seq.int(nrow(Marist))
dim(Marist)
```

```{r}
TIPPIBD <- Total %>% filter(poll == "IBD/TIPPIBD/TIPP")
TIPPIBD$Week<- seq.int(nrow(TIPPIBD))
dim(TIPPIBD)
```
```{r}
Pew <- Total %>% filter(poll == "Pew ResearchPew")
Pew$Week<- seq.int(nrow(Pew))
dim(Pew)

```
```{r}
McClatchy <- Total %>% filter(poll =="McClatchy/MaristMcClatchy")
McClatchy$Week<- seq.int(nrow(McClatchy))
dim(McClatchy)
```

```{r}
Monmouth <- Total %>% filter(poll == "MonmouthMonmouth")
Monmouth$Week<- seq.int(nrow(Monmouth))
dim(Monmouth)
```

```{r}
USAToday <- Total %>% filter(poll == "USA Today/SuffolkUSA Today")
USAToday$Week<- seq.int(nrow(USAToday))
dim(USAToday)
```


```{r}
RCPAverage <- Total %>% filter(poll == "RCP Average")
RCPAverage$Week<- seq.int(nrow(RCPAverage))
dim(RCPAverage)
```

```{r}
Emerson <- Total %>% filter(poll == "EmersonEmerson")
Emerson$Week<- seq.int(nrow(Emerson))
dim(Emerson)
```


```{r}
total1 <- rbind(USAToday, Monmouth, McClatchy, Pew, TIPPIBD, Quinnipiac, Reuters, Marist, Emerson, PPP, WaPoABC, NBCWSJ, CBS, Economist, CNN, Fox, Rasmussen, Gallup)
dim(total1)
# dim(Total)

```

```{r, fig.height=4, fig.width=8, message=FALSE, warning=FALSE}
# Pollsr$approve <- as.numeric(Pollsr$approve)
# Pollsr$disapprove <- as.numeric(Pollsr$disapprove)
# Pollsr$spread <- as.numeric(Pollsr$spread)
# head(Pollsr)




```



```{r}
library(lubridate)
Gallup.ts <- ts(Gallup$approve, 
   freq=365.25/7, 
   start=decimal_date(ymd("2017-01-24"))) 
plot(Gallup.ts)

```


```{r}
setwd("/Users/Chris Iyer/Documents/R/myrepo/")
polls2 <- read.csv("PollingData.csv", header = T)
kable(polls2)
```

```{r}
iCitizen <- polls2 %>% filter(poll == "icitizen")
iCitizen$date <- (as.Date(c('2017-04-25', '2017-04-18', '2017-04-11', '2017-04-04', '2017-03-28', '2017-03-21', '2017-03-14')))

iCitizen <- iCitizen[nrow(iCitizen):1, ]
iCitizen$Week <- seq.int(nrow(iCitizen))
iCitizen

b <- ggplot(data=iCitizen, aes(x=date, y= approve)) +
    geom_line(size=1, color = "slateblue") + geom_text(aes(label = approve), size = 3, hjust = 0.5, vjust = 3, position = "stack") + geom_point() + geom_smooth(method = "se")
b
```

```{r}
PublicPolicy <- polls2 %>% filter(poll == "Public Policy Polling")
PublicPolicy
PublicPolicy$date <- (as.Date(c('2017-04-18', '2017-03-28', '2017-03-12', '2017-02-22','2017-02-08', '2017-01-31', '2017-01-24')))

PublicPolicy <- PublicPolicy[nrow(PublicPolicy):1, ]
PublicPolicy$Week <- seq.int(nrow(PublicPolicy))
PublicPolicy
cor(PublicPolicy$Week, PublicPolicy$approve)
b <- ggplot(data=PublicPolicy, aes(x=date, y= approve)) +
    geom_line(size=1, color = "slateblue") + geom_text(aes(label = approve), size = 3, hjust = 0.5, vjust = 3, position = "stack") + geom_point() + geom_smooth(method = "se")
b
```



```{r}
YouGov <- polls2 %>% filter(poll == "YouGov")
YouGov$date <- as.Date(c((as.Date(c('2017-05-09', '2017-05-02' ,'2017-04-25', '2017-04-18', '2017-04-11','2017-04-04', '2017-03-28', '2017-03-21', '2017-03-14', '2017-03-07', '2017-02-28', '2017-02-21','2017-02-18', '2017-02-14', '2017-02-07', '2017-01-31', '2017-01-24')))))
YouGov <- YouGov[nrow(YouGov):1, ]
YouGov$Week <- seq.int(nrow(YouGov))
dim(YouGov)
dim(Economist)
c <- ggplot(data = YouGov, aes(x = date, y = approve)) + geom_line(size=1, color = "slateblue")
c
YouCitizen <- rbind(YouGov, iCitizen)
YouCitizen

d <- ggplot(data = YouCitizen, aes(x = date, y = approve, group = poll, color = poll)) + geom_line(size=1) + geom_text(aes(label = approve), size = 3, hjust = 0.5, vjust = 3, position = "stack") + geom_point() + geom_smooth(method = "lm")
d
```


```{r}
RasmussenReports <- polls2 %>% filter(poll == "Rasmussen Reports/Pulse Opinion Research")
dim(RasmussenReports)
RasmussenReports$date <- (as.Date(c('2017-05-10', '2017-05-07', '2017-05-02', '2017-04-27',  '2017-04-24',  '2017-04-19', '2017-04-16', '2017-04-11','2017-04-06',  '2017-04-03', '2017-03-29', '2017-03-26','2017-03-21', '2017-03-16', '2017-03-13','2017-03-08', '2017-03-05', '2017-02-28', '2017-02-23','2017-02-20', '2017-02-15', '2017-02-12', '2017-02-07', '2017-02-02', '2017-01-30', '2017-01-25')))
dim(RasmussenReports$date)
RasmussenReports <- RasmussenReports[nrow(RasmussenReports):1, ]
RasmussenReports$Week <- seq.int(nrow(RasmussenReports))
RasmussenReports
b <- ggplot(data=RasmussenReports, aes(x=date, y= approve)) +
    geom_line(size=1, color = "slateblue") + geom_text(aes(label = approve), size = 3, hjust = 0.5, vjust = 3, position = "stack") + geom_point() + geom_smooth(method = "lm")
b

```


```{r}
MorningConsult <- polls2 %>% filter(poll == "Morning Consult")
dim(MorningConsult)

MorningConsult$date <- (as.Date(c('2017-05-09', '2017-05-02' ,'2017-04-25', '2017-04-18', '2017-04-11', '2017-04-04', '2017-03-28', '2017-03-21', '2017-03-14', '2017-03-07', '2017-02-28', '2017-02-21', '2017-02-14', '2017-02-07', '2017-01-31', '2017-01-24')))
MorningConsult <- MorningConsult[nrow(MorningConsult):1, ]
MorningConsult$Week <- seq.int(nrow(MorningConsult))
MorningConsult
b <- ggplot(data=MorningConsult, aes(x=date, y= approve)) +
    geom_line(size=1, color = "slateblue") + geom_text(aes(label = approve), size = 3, hjust = 0.5, vjust = 3, position = "stack") + geom_point() + geom_smooth(method = "se")
b
```

```{r}
Ipsos <- polls2 %>% filter(poll == "Ipsos")
dim(Ipsos)

Ipsos$date <- (as.Date(c('2017-05-08', '2017-05-03' ,'2017-04-28', '2017-04-23', '2017-04-18','2017-04-13', '2017-04-08', '2017-04-03','2017-03-29', '2017-03-24', '2017-03-19', '2017-03-14', '2017-03-09', '2017-03-04','2017-02-27', '2017-02-22', '2017-02-17', '2017-02-12', '2017-02-07','2017-02-02', '2017-01-28')))
Ipsos <- Ipsos[nrow(Ipsos):1, ]
Ipsos$Week <- seq.int(nrow(Ipsos))
Ipsos
b <- ggplot(data=Ipsos, aes(x=date, y= approve)) +
    geom_line(size=1, color = "slateblue") + geom_text(aes(label = approve), size = 3, hjust = 0.5, vjust = 3, position = "stack") + geom_point() + geom_smooth(method = "lm")
b
```

```{r}
Pew <- polls2 %>% filter(poll == "Pew Research Center")
dim(Pew)

Pew$date <- (as.Date(c('2017-04-11','2017-03-12', '2017-02-12')))
Pew<- Pew[nrow(Pew):1, ]
Pew$Week <- seq.int(nrow(Pew))
Pew
b <- ggplot(data=Pew, aes(x=date, y= approve)) +
    geom_line(size=1, color = "slateblue") + geom_text(aes(label = approve), size = 3, hjust = 0.5, vjust = 3, position = "stack") + geom_point() + geom_smooth(method = "lm")
b
```




```{r, fig.height=8, fig.width=8}

Gallup1 <- polls2 %>% filter(poll == "Gallup")
dim(Gallup)
SurveyMonkey <- polls2 %>% filter(poll == "SurveyMonkey")
SurveyMonkey$date <- as.Date(c('2017-05-09', '2017-05-02' ,'2017-04-25', '2017-04-18', '2017-04-11','2017-04-04', '2017-03-28', '2017-03-21', '2017-03-14', '2017-03-07', '2017-02-28', '2017-02-21','2017-02-18', '2017-02-14', '2017-02-07', '2017-01-31', '2017-01-24'))
SurveyMonkey <- SurveyMonkey[nrow(SurveyMonkey):1, ]
SurveyMonkey$Week <- seq.int(nrow(SurveyMonkey))
SurveyMonkey

YouCitizenMonkey <- rbind(YouGov, iCitizen, SurveyMonkey, RasmussenReports, MorningConsult, Ipsos, Pew, PublicPolicy)
YouCitizenMonkey

d <- ggplot(data = YouCitizenMonkey, aes(x = date, y = approve, group = poll, color = poll)) + geom_point() + facet_wrap(~ poll) + geom_smooth(method = "lm", color = "grey", se = FALSE)

# + geom_text(aes(label = approve), size = 3, hjust = 0.5, vjust = 3, position = "stack") 
d
```


```{r}

fit1 <- lm(Week ~ approve, data = Fox)
summary(fit1)
d <- ggplot(data = YouCitizenMonkey, aes(x = date, y = approve, group = poll, color = poll)) + geom_line(size = 0.25, color = "black") + geom_point() + facet_wrap(~ poll) + geom_smooth(method = "lm", color = "grey", se = FALSE)
d
```







```{r}
a <- ggplot(data=Pollsr, aes(x=date, y= approve, group=poll, color = poll)) +
    geom_line(size=1) 
a
```


```{r}
a <- ggplot(data=YouCitizen, aes(x=date, y= approve, group=poll, color = poll)) +
    geom_line(size=1) 
a
```








