---
title: "SalesPipeline"
author: "Christine Iyer"
date: "August 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(knitr)
library(cowplot)


```




```{r}
salesData <- read.csv("SalesData.csv", header = T)
names(salesData)
max(salesData$Opportunity.Number) - min(salesData$Opportunity.Number)
dim(salesData)
str(salesData)
kable(head(salesData))

```


```{r}
ggplot(salesData, aes(x = Supplies.Subgroup, fill = Opportunity.Result)) + geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip()+ labs(y = "Count") + 
    scale_fill_manual(values=c("#44AA77", "#114477")) + theme_bw()
```

```{r}
ggplot(salesData, aes(x = Region, fill = Opportunity.Result)) + geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip()+ labs(y = "Count") + 
    scale_fill_manual(values=c("#44AA77", "#114477")) + theme_bw()
```

[Nice Colors](https://www.r-bloggers.com/the-paul-tol-21-color-salute/)

```{r}
tim12equal = c("#00008F", "#0000EA", "#0047FF", "#00A2FF", "#00FEFF", "#5AFFA5", "#B5FF4A", "#FFED00", "#FF9200", "#FF3700", "#DB0000", "#800000", "#6699CC", "#88CCEE")
tol11qualitative=c("#332288", "#6699CC", "#88CCEE", "#44AA99", "#117733", "#999933", "#DDCC77", "#661100", "#CC6677", "#00A2FF", "#00FEFF")
tol21rainbow= c("#771155", "#AA4488", "#CC99BB", "#114477", "#4477AA", "#77AADD", "#117777", "#44AAAA", "#77CCCC", "#117744", "#44AA77", "#88CCAA", "#777711", "#AAAA44", "#DDDD77", "#774411", "#AA7744", "#DDAA77", "#771122", "#AA4455", "#DD7788")
salesPlotx <- ggplot(salesData, aes(x = Region, fill = Supplies.Subgroup)) + geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip()  + theme_bw() + labs(y = "Count")  +
    scale_fill_manual(values=tol21rainbow)
#+ theme(legend.position="none")
salesPlotx
salesPlotxx <- salesPlotx %+% subset(salesData, Opportunity.Result %in% c("Won") )
plot_grid(salesPlotx, salesPlotxx, align='h', labels=c('All', 'Won')) + scale_x_discrete(name ="Dose (mg)", 
                    limits=c("0","60000","1000"))
```

“What are the top supplies group by opportunity amount where result is won?”.  You will note on the insights bar after looking at this exploration “Top Route to Market by Opportunity Size”, you may want to add this to your exploration!


```{r}
ggplot(salesData, aes(x = Supplies.Group, y = Opportunity.Amount.USD, fill = Opportunity.Result )) + geom_bar(stat = "identity", position = "dodge") 
#+ scale_y_continuous(breaks=c(1000, 2000, 3000, 4000, 5000, 10000, 20000, 30000, 40000, 50000))


```

Route to Market

```{r}
ggplot(salesData, aes(x = Region, fill = Route.To.Market)) + geom_bar()+ theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  coord_flip()  + theme_bw() + labs(y = "Count")  +
    scale_fill_manual(values=tol21rainbow)
```

```{r}

groupedSalesData <- salesData %>% group_by(Supplies.Subgroup) %>% summarise(n = n(), amount = sum(Opportunity.Amount.USD)) %>% mutate(freq = (n/sum(n)))

groupedSalesXXX <- aggregate(salesData$Opportunity.Amount.USD, by = list(salesData$Supplies.Subgroup), sum)

groupedSalesXXX <-  groupedSalesXXX %>% mutate(OpporResultInMillions = (round(x/1000000 ,0))) %>% rename(Supplies.Subgroup = Group.1)
kable(groupedSalesXXX)

salesData1 <- inner_join(salesData, groupedSalesXXX)
dim(salesData1)
ggplot(salesData1, aes(x = Region, y = Opportunity.Amount.USD/1000000, fill = factor(OpporResultInMillions))) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + labs(y = "Sales in $ (millions)", title = "Supplies Sales by Region") + theme_bw() + scale_fill_manual(values = tol21rainbow,name="Supplies\nSubgroup",
labels=c("Car Electronics","Tires & Wheels","Performance Parts", "Towing & Hitches", "Replacement Parts", "Garage & Car Care", "Interior Accessories", "Batteries & Accessories", "Motorcycle Parts", "Exterior Accessories", "Shelters & RV"))
```


```{r}
library(reshape2)
# creating a data samples
# content
df.content <- data.frame(content = c('main', 'ad landing',
'product 1', 'product 2', 'product 3', 'product 4',
'shopping cart',
'thank you page'),
step = c('awareness', 'awareness',
'interest', 'interest', 'interest', 'interest',
'desire',
'action'),
number = c(150000, 80000,
80000, 40000, 35000, 25000,
130000,
120000))
# customers
df.customers <- data.frame(content = c('new', 'engaged', 'loyal'),
step = c('new', 'engaged', 'loyal'),
number = c(25000, 40000, 55000))
# combining two data sets
df.all <- rbind(df.content, df.customers)


kable(df.all)

```

```{r}
# calculating dummies, max and min values of X for plotting
df.all <- df.all %>%
group_by(step) %>%
mutate(totnum = sum(number)) %>%
ungroup() %>%
mutate(dum = (max(totnum) - totnum)/2,
maxx = totnum + dum,
minx = dum)
kable(df.all)
```

 
 
```{r} 
# calculating dummies, max and min values of X for plotting
df.all <- df.all %>%
group_by(step) %>%
mutate(totnum = sum(number)) %>%
ungroup() %>%
mutate(dum = (max(totnum) - totnum)/2,
maxx = totnum + dum,
minx = dum)
kable(df.all)
```
 
```{r} 
# data frame for plotting funnel lines
df.lines <- df.all %>%
select(step, maxx, minx) %>%
group_by(step) %>%
unique()
 df.lines
``` 



```{r} 
# data frame with dummies
df.dum <- df.all %>%
select(step, dum) %>%
unique() %>%
mutate(content = 'dummy',
number = dum) %>%
select(content, step, number)
 
df.dum
```  

```{r}
# data frame with rates
conv <- df.all$totnum[df.all$step == 'action']
 
df.rates <- df.all %>%
select(step, totnum) %>%
group_by(step) %>%
unique() %>%
ungroup() %>%
mutate(prevnum = lag(totnum),
rate = ifelse(step == 'new' | step == 'engaged' | step == 'loyal',
round(totnum / conv, 3),
round(totnum / prevnum, 3))) %>%
select(step, rate)
df.rates <- na.omit(df.rates)

df.rates
```


```{r}
# creting final data frame
df.all <- df.all %>%
select(content, step, number)
 
df.all <- rbind(df.all, df.dum)
 
df.all <- df.all %>%
group_by(step) %>%
arrange(desc(content)) %>%
ungroup()
df.all
```

```{r}
# calculating position of labels
df.all <- df.all %>%
group_by(step) %>%
mutate(pos = cumsum(number) - 0.5*number)
df.all
```

```{r}

names(df.all)
# defining order of steps
df.all$step <- factor(df.all$step, levels = c('loyal', 'engaged', 'new', 'action', 'desire', 'interest', 'awareness'))
list <- c(unique(as.character(df.all$content)))
#df.all$content <- factor(df.all$content, levels = c('dummy', c(list)))
 
```


```{r}
# creating custom palette with 'white' color for dummies
cols <- c("#ffffff", "#fec44f", "#fc9272", "#a1d99b", "#fee0d2", "#2ca25f",
"#8856a7", "#43a2ca", "#fdbb84", "#e34a33",
"#a6bddb", "#dd1c77", "#ffeda0", "#756bb1")
 
# plotting chart
ggplot() +
theme_minimal() +
coord_flip() +
scale_fill_manual(values=cols) +
geom_bar(data=df.all, aes(x=step, y=number, fill=content), stat="identity", width=1) +
geom_text(data=df.all[df.all$content!='dummy', ],
aes(x=step, y=pos, label=paste0(content, '-', number/1000, 'K')),
size=4, color='white', fontface="bold") +
geom_ribbon(data=df.lines, aes(x=step, ymax=max(maxx), ymin=maxx, group=1), fill='white') +
geom_line(data=df.lines, aes(x=step, y=maxx, group=1), color='darkred', size=4) +
geom_ribbon(data=df.lines, aes(x=step, ymax=minx, ymin=min(minx), group=1), fill='white') +
geom_line(data=df.lines, aes(x=step, y=minx, group=1), color='darkred', size=4) +
geom_text(data=df.rates, aes(x=step, y=(df.lines$minx[-1]), label=paste0(rate*100, '%')), hjust=1.2,
color='darkblue', fontface="bold") +
theme(legend.position='none', axis.ticks=element_blank(), axis.text.x=element_blank(),
axis.title.x=element_blank())
```

```{r}
profitCost <- read.csv("ProfitCost.csv", header = T)
head(profitCost)
profitCost <- profitCost %>% na.omit()
ggplot(profitCost, aes(x = Product.line, y = Revenue/1000000, fill = Retailer.country)) + geom_bar(stat = "identity") +
  coord_flip()+ labs(y = "Rev in Millions")
```

