---
title: "Lies"
author: "Christine Iyer"
date: "June 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(rvest)
library(tidytext)
library(dplyr)
library(stringr)


library(tidyr)
library(reshape2)
library(knitr)
library(lubridate)

```

```{r}
Lies1 <- read_html("http://www.politifact.com/personalities/donald-trump/statements/byruling/false/")
Statement <- Lies1 %>% html_nodes(".statement__text") %>% html_text()
month <- Lies1 %>% html_nodes(".article__meta") %>% html_text()
page1 <- cbind(month, Statement)


Lies2 <- read_html("http://www.politifact.com/personalities/donald-trump/statements/byruling/false/?page=2")
Statement2 <- Lies2 %>% html_nodes(".statement__text") %>% html_text()
month2 <- Lies2 %>% html_nodes(".article__meta") %>% html_text()
page2 <- cbind(month2, Statement2)

Lies3 <- read_html("http://www.politifact.com/personalities/donald-trump/statements/byruling/false/?page=3")
Statement3 <- Lies3 %>% html_nodes(".statement__text") %>% html_text()
month3 <- Lies3 %>% html_nodes(".article__meta") %>% html_text()
page3 <- cbind(month3, Statement3)

Lies4 <- read_html("http://www.politifact.com/personalities/donald-trump/statements/byruling/false/?page=4")
Statement4 <- Lies4 %>% html_nodes(".statement__text") %>% html_text()
month4 <- Lies4 %>% html_nodes(".article__meta") %>% html_text()
page4 <- cbind(month4, Statement4)

Lies5 <- read_html("http://www.politifact.com/personalities/donald-trump/statements/byruling/false/?page=5")
Statement5 <- Lies5 %>% html_nodes(".statement__text") %>% html_text()
month5 <- Lies5 %>% html_nodes(".article__meta") %>% html_text()
page5 <- cbind(month5, Statement5)

Lies6 <- read_html("http://www.politifact.com/personalities/donald-trump/statements/byruling/false/?page=6")
Statement6 <- Lies6 %>% html_nodes(".statement__text") %>% html_text()
month6 <- Lies6 %>% html_nodes(".article__meta") %>% html_text()
page6 <- cbind(month6, Statement6)

Lies7 <- read_html("http://www.politifact.com/personalities/donald-trump/statements/byruling/false/?page=7")
Statement7 <- Lies7 %>% html_nodes(".statement__text") %>% html_text()
month7 <- Lies7 %>% html_nodes(".article__meta") %>% html_text()
page7 <- cbind(month7, Statement7)
```

```{r}
x <- rbind(page1, page2, page3, page4, page5, page6, page7)
class(x)
kable(head(x))




#convert to data frame
x <- as.data.frame(x)
#confirm conversion
str(x)
#edit the month column
x$month <- gsub("on ", "", paste(x$month))

suffix <- c("th", "nd", "st", "rd")
x$month <-  gsub(suffix, '', x$month)

x$month <- substring(x$month, 8)
x[c(4, 6, 11,14,18,26, 30:31, 38, 54, 58, 60, 66:67, 70, 83:84, 86, 88,91:93,97:99, 102, 105:106, 113, 120, 127,133),1]<- substring(x[c(4, 6, 11,14,18,26, 30:31, 38, 54, 58, 60, 66:67, 70, 83:84, 86, 88,91:93,97:99, 102, 105:106, 113, 120,127, 133),1], 3)

x[c(15, 20, 27, 46, 49:51, 61, 68:69, 72:74, 78:80, 85, 104, 109, 112, 123 ),1]<- substring(x[c(15, 20, 27, 46, 49:51, 61, 68:69, 72:74, 78:80, 85, 104, 109, 112, 123 ),1], 4)

x[c(7:8, 22, 32:34, 39:43, 55:56,65, 81, 94, 101,110, 121, 124, 128:129,131 ),1]<- substring(x[c(7:8, 22, 32:34, 39:43, 55:56,65, 81, 94, 101, 110, 121, 124, 128:129, 131 ),1], 2)


kable(tail(x))
x$month <- gsub("January", "01-", paste(x$month))
x$month <- gsub("February", "02-", paste(x$month))
x$month <- gsub("March", "03-", paste(x$month))
x$month <- gsub("April", "04-", paste(x$month))
x$month <- gsub("May", "05-", paste(x$month))
x$month <- gsub("June", "06-", paste(x$month))
x$month <- gsub("July", "07-", paste(x$month))
x$month <- gsub("August", "08-", paste(x$month))
x$month <- gsub("September", "09-", paste(x$month))
x$month <- gsub("October", "10-", paste(x$month))
x$month <- gsub("November", "11-", paste(x$month))
x$month <- gsub("December", "12-", paste(x$month))

x$month <- gsub(",", "-", paste(x$month))
x$month <- gsub("st", "", paste(x$month))
x$month <- gsub("nd", "", paste(x$month))
x$month <- gsub("rd", "", paste(x$month))
x$month <- as.Date(x$month, format = "%m-%d-%Y")

x$ID <- seq.int(nrow(x))
kable(head(x %>%  select(ID, month, Statement)))



```

```{r}
dim(x)
reg <- "([^A-Za-z\\d#@']|'(?![A-Za-z\\d#@]))"
df <- data.frame(string = c(1:134), x$month, text = x$Statement)
kable(head(df))
df %>% unnest_tokens(word, text, token = "regex", pattern = reg)
# stop words and can use the stop_words list that comes with tidytext
df %>% unnest_tokens(word, text, token = "regex", pattern = reg) %>%
  filter(!word %in% stop_words$word)
words_df <- df %>% unnest_tokens(word, text, token = "regex", pattern = reg) %>%
  filter(!word %in% stop_words$word,
         str_detect(word, "[a-z]"))
head(words_df)
bing <- sentiments %>%
  filter(lexicon == "bing")
finn <- sentiments %>%
  filter(lexicon == "AFINN")
nrc <- sentiments %>%
  filter(lexicon == "nrc")

#bing
# kable(head(words_df %>% inner_join(bing, by="word")%>%   group_by(string) %>% 
#   summarize(score = sum(score)) %>%
#   inner_join(df, by = "string")))
#finn
kable(words_df %>% inner_join(finn, by="word")%>% 
  group_by(string) %>% 
  summarize(score = sum(score)) %>%
  inner_join(df, by = "string"))
#nrc
# kable(words_df %>% inner_join(nrc, by="word") %>% 
#   group_by(string) %>% 
#   summarize(score = sum(score)) %>%
#   inner_join(df, by = "string"))


```



```{r, echo=TRUE}
dim(df)
#df <- data.frame(string, text)
reg <- "([^A-Za-z\\d@']|'(?![A-Za-z\\d@]))"
words_df <- df %>% unnest_tokens(word, text, token = "regex", pattern = reg) %>%
  filter(!word %in% stop_words$word,
         str_detect(word, "[a-z]"))

dim(words_df)
words_df <- words_df %>% inner_join(finn, by = "word") %>% 
  group_by(string) %>% 
   summarize(score = sum(score)) %>%
  inner_join(df, by = "string")

words_df
```

```{r}
library(ggplot2)
range(words_df$score)
words_df <- words_df %>% mutate(Negativity_Scale = ifelse(score <= 0, "Negative Tone", "Positive Tone"))

words_df <- words_df %>% filter(x.month > "2016-11-09")
g <- ggplot(words_df, aes(x = x.month, y = score, color = factor(Negativity_Scale), size = score)) + geom_point(values = c("red", "blue")) 
g
```


